"""
Bot xabarlari — O'zbek va Rus tillarida.
"""

TEXTS = {
    "ru": {
        "start_new": "👋 Добро пожаловать в <b>Саломат билимдонлари</b>!\n\nВыберите язык:",
        "start_welcome_parent": "👋 Добро пожаловать, {name}!\n\n📊 Вы вошли как <b>родитель</b>.",
        "start_welcome_admin": "👋 Добро пожаловать, <b>Администратор</b>!\n\nВы вошли в <b>Панель управления</b>.",
        "lang_changed": "✅ Язык изменён на Русский",
        "no_children": "😔 Ваш Telegram ID не привязан ни к одному ученику.\n\n📋 Сообщите учителю ваш Chat ID: <code>{chat_id}</code>\nПопросите добавить его в профиль вашего ребёнка.",
        "children_list": "👨‍👩‍👧 <b>Ваши дети:</b>",
        "child_results_title": "📊 <b>Результаты: {name} {last}</b> ({cls})\n\n",
        "no_results": "📭 Пока нет результатов для этого ученика.",
        "result_row": "📝 <b>{test}</b>\n   📊 {score:.1f}% | {grade} | {status}\n   🕐 {date}\n\n",
        "passed": "✅ Сдал",
        "failed": "❌ Не сдал",
        "back": "⬅️ Назад",
        "main_menu": "🏠 Главное меню",
        "settings_btn": "⚙️ Настройки",
        "lang_btn": "🌐 Сменить язык",
        "children_btn": "👨‍👩‍👧 Мои дети",
        "results_btn": "📊 Результаты",
        "not_admin": "❌ У вас нет прав администратора.",
        "admin_menu_title": "🔧 <b>Панель администратора</b>\n\nВыберите раздел:",
        "stats_btn": "📈 Статистика",
        "students_btn": "👥 Ученики",
        "questions_btn": "❓ Вопросы",
        "subjects_btn": "📚 Предметы",
        "top_btn": "🏆 Топ учеников",
        "broadcast_btn": "📢 Рассылка",
        "admins_btn": "👤 Администраторы",
        "export_btn": "📊 Excel yuklab olish",
        "export_choose": "📊 <b>Excel eksport</b>\n\nQaysi testning natijalarini yuklab olishni tanlang:",
        "export_all_btn": "📥 Barcha natijalar ({n} ta)",
        "export_wait": "⏳ Fayl tayyorlanmoqda...",
        "export_empty": "😔 Hech qanday natija topilmadi.",
        "export_done": "✅ Excel fayl tayyor — {n} ta natija.",
        "stats_title": "📈 <b>Общая статистика</b>\n\n",
        "stats_total_exams": "📝 Всего экзаменов: <b>{n}</b>\n",
        "stats_passed": "✅ Сдали: <b>{n}</b>\n",
        "stats_failed": "❌ Не сдали: <b>{n}</b>\n",
        "stats_avg": "📊 Средний балл: <b>{v:.1f}%</b>\n",
        "stats_students": "👥 Учеников: <b>{n}</b>\n",
        "stats_classes": "🏫 Классов: <b>{n}</b>\n",
        "stats_questions": "❓ Вопросов: <b>{n}</b>\n",
        "top_title": "🏆 <b>Топ 10 учеников</b>\n\n",
        "top_row": "{rank}. <b>{last} {first}</b> ({cls}) — {score:.1f}% | {test}\n",
        "no_top": "Пока нет данных.",
        "subjects_title": "📚 <b>Предметы ({n}):</b>\n\n",
        "subject_row": "• {name} — {q} вопросов\n",
        "no_subjects": "Предметов пока нет.",
        "broadcast_ask": "📢 <b>Рассылка родителям</b>\n\nНапишите сообщение для отправки всем родителям:",
        "broadcast_confirm": "📢 Отправить это сообщение <b>{n} родителям</b>?\n\n<i>{text}</i>",
        "broadcast_sent": "✅ Сообщение отправлено {ok} из {total} родителям.",
        "broadcast_cancel": "❌ Рассылка отменена.",
        "confirm_btn": "✅ Подтвердить",
        "cancel_btn": "❌ Отмена",
        "add_question_btn": "➕ Добавить вопрос",
        "q_choose_subject": "📚 Выберите предмет для вопроса:",
        "q_ask_text": "✏️ Введите текст вопроса:",
        "q_ask_a": "✅ Введите вариант <b>A</b>:",
        "q_ask_b": "📘 Введите вариант <b>B</b>:",
        "q_ask_c": "🟠 Введите вариант <b>C</b>:",
        "q_ask_d": "🔴 Введите вариант <b>D</b>:",
        "q_ask_correct": "✔️ Какой вариант правильный? Выберите:",
        "q_ask_diff": "📊 Выберите сложность:",
        "q_diff_easy": "🟢 Лёгкий",
        "q_diff_med": "🟡 Средний",
        "q_diff_hard": "🔴 Сложный",
        "q_confirm": "✅ <b>Проверьте вопрос:</b>\n\n📝 {text}\n\nA: {a}\nB: {b}\nC: {c}\nD: {d}\n\n✔️ Правильный: <b>{correct}</b>\n📊 Сложность: {diff}",
        "q_saved": "✅ Вопрос успешно сохранён! (ID: {id})",
        "q_cancel": "❌ Добавление вопроса отменено.",
        "admins_title": "👤 <b>Бот-администраторы:</b>\n\n{list}\n\nВыберите действие:",
        "no_admins": "Администраторов пока нет.",
        "admin_row": "• <code>{tid}</code> {name}\n",
        "admin_add_btn": "➕ Добавить администратора",
        "admin_del_btn": "🗑 Удалить администратора",
        "admin_add_prompt": "📲 Введите <b>Telegram ID</b> нового администратора:\n\n<i>Чтобы узнать свой ID, напишите @userinfobot</i>",
        "admin_add_invalid": "❌ Неверный формат. Введите числовой Telegram ID:",
        "admin_add_exists": "⚠️ Этот ID уже является администратором!",
        "admin_add_confirm": "➕ Добавить администратора <code>{tid}</code>?",
        "admin_added": "✅ Администратор <code>{tid}</code> успешно добавлен!",
        "admin_del_prompt": "Выберите администратора для удаления:",
        "admin_del_self": "⚠️ Нельзя удалить самого себя!",
        "admin_del_confirm": "🗑 Удалить администратора <code>{tid}</code>?",
        "admin_deleted": "✅ Администратор <code>{tid}</code> удалён.",
        "admin_not_found": "❌ Администратор не найден.",
        "students_classes": "🏫 <b>Классы:</b>",
        "class_row": "• {name} — {n} учеников",
        "students_of_class": "👥 <b>Ученики класса {cls}:</b>\n\n",
        "student_row": "{i}. {last} {first}",
        "no_students_in_class": "В этом классе пока нет учеников.",
        "error": "❌ Произошла ошибка. Попробуйте снова.",
        "refresh_btn": "🔄 Обновить",
        "close_btn": "✖ Закрыть",
        # Fan yaratish
        "fan_add_btn": "➕ Добавить предмет",
        "fan_add_ask_name": "📚 Введите название предмета:",
        "fan_add_ask_time": "⏱ Введите лимит времени в минутах (например: <b>30</b>):",
        "fan_add_time_invalid": "❌ Введите только число (например: 30):",
        "fan_add_confirm": "✅ <b>Добавить предмет?</b>\n\n📚 Название: <b>{name}</b>\n⏱ Время: <b>{time} мин</b>",
        "fan_add_saved": "✅ Предмет добавлен: <b>{name}</b>",
        "fan_add_cancel": "❌ Добавление предмета отменено.",
        # Sinf qo'shish
        "cls_add_btn": "➕ Добавить класс",
        "cls_add_ask_name": "🏫 Введите название класса (например: <b>9-A</b>):",
        "cls_add_confirm": "✅ <b>Добавить класс?</b>\n\n🏫 Название: <b>{name}</b>",
        "cls_add_saved": "✅ Класс добавлен: <b>{name}</b>",
        "cls_add_cancel": "❌ Добавление класса отменено.",
        # O'quvchi qo'shish
        "std_add_btn": "➕ Добавить ученика",
        "std_add_ask_fname": "👤 Введите <b>имя</b> ученика:",
        "std_add_ask_lname": "👤 Введите <b>фамилию</b> ученика:",
        "std_add_ask_parent": "📱 Введите Telegram ID родителя\n(или нажмите <b>Пропустить</b>):",
        "std_add_skip_btn": "⏭ Пропустить",
        "std_add_confirm": (
            "✅ <b>Добавить ученика?</b>\n\n"
            "👤 Имя: <b>{first}</b>\n"
            "👤 Фамилия: <b>{last}</b>\n"
            "🏫 Класс: <b>{cls}</b>\n"
            "📱 Telegram ID родителя: <b>{parent}</b>"
        ),
        "std_add_saved": "✅ Ученик добавлен: <b>{last} {first}</b> → {cls}",
        "std_add_cancel": "❌ Добавление ученика отменено.",
        # Fan boshqaruvi
        "active": "✅ Активен",
        "inactive": "❌ Неактивен",
        "fan_detail": "📚 <b>{name}</b>\n⏱ Время: {time} мин\n❓ Вопросов: {q}\n🔘 Статус: {status}",
        "fan_add_q_btn": "➕ Добавить вопрос",
        "fan_activate_btn": "✅ Активировать",
        "fan_deactivate_btn": "❌ Деактивировать",
        "fan_delete_btn": "🗑 Удалить предмет",
        "fan_del_ask": "🗑 Удалить предмет <b>{name}</b>?\n\n⚠️ Связанные вопросы останутся, но предмет исчезнет из списков.",
        "fan_deleted": "✅ Предмет удалён: <b>{name}</b>",
        "fan_toggled_on": "✅ Предмет активирован: <b>{name}</b>",
        "fan_toggled_off": "❌ Предмет деактивирован: <b>{name}</b>",
        "del_confirm_btn": "🗑 Да, удалить",
        "del_cancel_btn": "❌ Отмена",
        # Sinf boshqaruvi
        "cls_detail": "🏫 <b>{name}</b>\n👥 Учеников: {n}\n🔘 Статус: {status}",
        "cls_edit_btn": "✏️ Переименовать",
        "cls_edit_ask": "✏️ <b>{name}</b> классини новое название:",
        "cls_edited": "✅ Класс переименован: <b>{name}</b>",
        "cls_activate_btn": "✅ Активировать",
        "cls_deactivate_btn": "❌ Деактивировать",
        "cls_delete_btn": "🗑 Удалить класс",
        "cls_view_students_btn": "👥 Ученики",
        "cls_del_ask": "🗑 Удалить класс <b>{name}</b>?\n\n⚠️ Все ученики класса тоже будут удалены!",
        "cls_deleted": "✅ Класс удалён: <b>{name}</b>",
        "cls_toggled_on": "✅ Класс активирован: <b>{name}</b>",
        "cls_toggled_off": "❌ Класс деактивирован: <b>{name}</b>",
        # O'quvchi boshqaruvi
        "std_detail": "👤 <b>{last} {first}</b>\n🏫 Класс: {cls}\n📱 TG родителя: {parent}",
        "std_edit_fname_btn": "✏️ Изменить имя",
        "std_edit_lname_btn": "✏️ Изменить фамилию",
        "std_edit_parent_btn": "📱 Изменить TG ID",
        "std_delete_btn": "🗑 Удалить ученика",
        "std_del_ask": "🗑 Удалить ученика <b>{last} {first}</b>?",
        "std_deleted": "✅ Ученик удалён: <b>{last} {first}</b>",
        "std_edit_ask_fname": "✏️ Введите новое <b>имя</b>:",
        "std_edit_ask_lname": "✏️ Введите новую <b>фамилию</b>:",
        "std_edit_ask_parent": "📱 Введите новый Telegram ID родителя\n(или нажмите <b>Пропустить</b> чтобы убрать):",
        "std_updated": "✅ Данные ученика обновлены: <b>{last} {first}</b>",
    },
    "uz": {
        "start_new": "👋 <b>Salomat bilimdonlari</b> ga xush kelibsiz!\n\nTilni tanlang:",
        "start_welcome_parent": "👋 Xush kelibsiz, {name}!\n\n📊 Siz <b>ota-ona</b> sifatida kirdingiz.",
        "start_welcome_admin": "👋 Xush kelibsiz, <b>Administrator</b>!\n\n<b>Boshqaruv paneli</b> ga xush kelibsiz.",
        "lang_changed": "✅ Til O'zbekchaga o'zgartirildi",
        "no_children": "😔 Sizning Telegram ID hech bir o'quvchiga biriktirilmagan.\n\n📋 O'qituvchiga Chat ID ni bering: <code>{chat_id}</code>\nO'quvchi profiliga kiritishni so'rang.",
        "children_list": "👨‍👩‍👧 <b>Farzandlaringiz:</b>",
        "child_results_title": "📊 <b>Natijalar: {name} {last}</b> ({cls})\n\n",
        "no_results": "📭 Bu o'quvchi uchun hali natijalar yo'q.",
        "result_row": "📝 <b>{test}</b>\n   📊 {score:.1f}% | {grade} | {status}\n   🕐 {date}\n\n",
        "passed": "✅ O'tdi",
        "failed": "❌ O'tmadi",
        "back": "⬅️ Orqaga",
        "main_menu": "🏠 Asosiy menyu",
        "settings_btn": "⚙️ Sozlamalar",
        "lang_btn": "🌐 Tilni o'zgartirish",
        "children_btn": "👨‍👩‍👧 Farzandlarim",
        "results_btn": "📊 Natijalar",
        "not_admin": "❌ Sizda admin huquqi yo'q.",
        "admin_menu_title": "🔧 <b>Admin paneli</b>\n\nBo'limni tanlang:",
        "stats_btn": "📈 Statistika",
        "students_btn": "👥 O'quvchilar",
        "questions_btn": "❓ Savollar",
        "subjects_btn": "📚 Fanlar",
        "top_btn": "🏆 Top o'quvchilar",
        "broadcast_btn": "📢 Xabar yuborish",
        "admins_btn": "👤 Adminlar",
        "export_btn": "📊 Excel yuklab olish",
        "export_choose": "📊 <b>Excel eksport</b>\n\nQaysi testning natijalarini yuklab olishni tanlang:",
        "export_all_btn": "📥 Barcha natijalar ({n} ta)",
        "export_wait": "⏳ Fayl tayyorlanmoqda...",
        "export_empty": "😔 Hech qanday natija topilmadi.",
        "export_done": "✅ Excel fayl tayyor — {n} ta natija.",
        "stats_title": "📈 <b>Umumiy statistika</b>\n\n",
        "stats_total_exams": "📝 Jami imtihonlar: <b>{n}</b>\n",
        "stats_passed": "✅ O'tdilar: <b>{n}</b>\n",
        "stats_failed": "❌ O'tmadilar: <b>{n}</b>\n",
        "stats_avg": "📊 O'rtacha ball: <b>{v:.1f}%</b>\n",
        "stats_students": "👥 O'quvchilar: <b>{n}</b>\n",
        "stats_classes": "🏫 Sinflar: <b>{n}</b>\n",
        "stats_questions": "❓ Savollar: <b>{n}</b>\n",
        "top_title": "🏆 <b>Top 10 O'quvchilar</b>\n\n",
        "top_row": "{rank}. <b>{last} {first}</b> ({cls}) — {score:.1f}% | {test}\n",
        "no_top": "Hozircha ma'lumot yo'q.",
        "subjects_title": "📚 <b>Fanlar ({n}):</b>\n\n",
        "subject_row": "• {name} — {q} ta savol\n",
        "no_subjects": "Hozircha fan yo'q.",
        "broadcast_ask": "📢 <b>Ota-onalarga xabar</b>\n\nBarcha ota-onalarga yuboriladigan xabarni yozing:",
        "broadcast_confirm": "📢 Bu xabarni <b>{n} ta ota-onaga</b> yuborasizmi?\n\n<i>{text}</i>",
        "broadcast_sent": "✅ Xabar {ok} ta ota-onadan {total} tasiga yuborildi.",
        "broadcast_cancel": "❌ Xabar yuborish bekor qilindi.",
        "confirm_btn": "✅ Tasdiqlash",
        "cancel_btn": "❌ Bekor qilish",
        "add_question_btn": "➕ Savol qo'shish",
        "q_choose_subject": "📚 Savol uchun fan tanlang:",
        "q_ask_text": "✏️ Savol matnini kiriting:",
        "q_ask_a": "✅ <b>A</b> variantini kiriting:",
        "q_ask_b": "📘 <b>B</b> variantini kiriting:",
        "q_ask_c": "🟠 <b>C</b> variantini kiriting:",
        "q_ask_d": "🔴 <b>D</b> variantini kiriting:",
        "q_ask_correct": "✔️ Qaysi variant to'g'ri? Tanlang:",
        "q_ask_diff": "📊 Qiyinlikni tanlang:",
        "q_diff_easy": "🟢 Oson",
        "q_diff_med": "🟡 O'rta",
        "q_diff_hard": "🔴 Qiyin",
        "q_confirm": "✅ <b>Savolni tekshiring:</b>\n\n📝 {text}\n\nA: {a}\nB: {b}\nC: {c}\nD: {d}\n\n✔️ To'g'ri: <b>{correct}</b>\n📊 Qiyinlik: {diff}",
        "q_saved": "✅ Savol muvaffaqiyatli saqlandi! (ID: {id})",
        "q_cancel": "❌ Savol qo'shish bekor qilindi.",
        "admins_title": "👤 <b>Bot-adminlar:</b>\n\n{list}\nHarakatni tanlang:",
        "no_admins": "Hozircha admin yo'q.",
        "admin_row": "• <code>{tid}</code> {name}\n",
        "admin_add_btn": "➕ Admin qo'shish",
        "admin_del_btn": "🗑 Admin o'chirish",
        "admin_add_prompt": "📲 Yangi adminning <b>Telegram ID</b> sini kiriting:\n\n<i>ID ni bilish uchun @userinfobot ga yozing</i>",
        "admin_add_invalid": "❌ Noto'g'ri format. Raqamli Telegram ID kiriting:",
        "admin_add_exists": "⚠️ Bu ID allaqachon admin!",
        "admin_add_confirm": "➕ <code>{tid}</code> ni admin qilish?",
        "admin_added": "✅ Admin <code>{tid}</code> muvaffaqiyatli qo'shildi!",
        "admin_del_prompt": "O'chirmoqchi bo'lgan adminni tanlang:",
        "admin_del_self": "⚠️ O'zingizni o'chira olmaysiz!",
        "admin_del_confirm": "🗑 <code>{tid}</code> adminni o'chirish?",
        "admin_deleted": "✅ Admin <code>{tid}</code> o'chirildi.",
        "admin_not_found": "❌ Admin topilmadi.",
        "students_classes": "🏫 <b>Sinflar:</b>",
        "class_row": "• {name} — {n} ta o'quvchi",
        "students_of_class": "👥 <b>{cls} sinf o'quvchilari:</b>\n\n",
        "student_row": "{i}. {last} {first}",
        "no_students_in_class": "Bu sinfda hozircha o'quvchi yo'q.",
        "error": "❌ Xato yuz berdi. Qayta urinib ko'ring.",
        "refresh_btn": "🔄 Yangilash",
        "close_btn": "✖ Yopish",
        # Fan yaratish
        "fan_add_btn": "➕ Fan qo'shish",
        "fan_add_ask_name": "📚 Fan nomini kiriting:",
        "fan_add_ask_time": "⏱ Vaqt chegarasini daqiqada kiriting (masalan: <b>30</b>):",
        "fan_add_time_invalid": "❌ Faqat son kiriting (masalan: 30):",
        "fan_add_confirm": "✅ <b>Fan qo'shilsinmi?</b>\n\n📚 Nom: <b>{name}</b>\n⏱ Vaqt: <b>{time} daqiqa</b>",
        "fan_add_saved": "✅ Fan qo'shildi: <b>{name}</b>",
        "fan_add_cancel": "❌ Fan qo'shish bekor qilindi.",
        # Sinf qo'shish
        "cls_add_btn": "➕ Sinf qo'shish",
        "cls_add_ask_name": "🏫 Sinf nomini kiriting (masalan: <b>9-A</b>):",
        "cls_add_confirm": "✅ <b>Sinf qo'shilsinmi?</b>\n\n🏫 Nom: <b>{name}</b>",
        "cls_add_saved": "✅ Sinf qo'shildi: <b>{name}</b>",
        "cls_add_cancel": "❌ Sinf qo'shish bekor qilindi.",
        # O'quvchi qo'shish
        "std_add_btn": "➕ O'quvchi qo'shish",
        "std_add_ask_fname": "👤 O'quvchining <b>ismini</b> kiriting:",
        "std_add_ask_lname": "👤 O'quvchining <b>familiyasini</b> kiriting:",
        "std_add_ask_parent": "📱 Ota-ona Telegram ID sini kiriting\n(yoki <b>O'tkazib yuborish</b> bosing):",
        "std_add_skip_btn": "⏭ O'tkazib yuborish",
        "std_add_confirm": (
            "✅ <b>O'quvchi qo'shilsinmi?</b>\n\n"
            "👤 Ismi: <b>{first}</b>\n"
            "👤 Familiyasi: <b>{last}</b>\n"
            "🏫 Sinf: <b>{cls}</b>\n"
            "📱 Ota-ona Telegram ID: <b>{parent}</b>"
        ),
        "std_add_saved": "✅ O'quvchi qo'shildi: <b>{last} {first}</b> → {cls}",
        "std_add_cancel": "❌ O'quvchi qo'shish bekor qilindi.",
        # Fan boshqaruvi
        "active": "✅ Faol",
        "inactive": "❌ Nofaol",
        "fan_detail": "📚 <b>{name}</b>\n⏱ Vaqt: {time} daqiqa\n❓ Savollar: {q} ta\n🔘 Holat: {status}",
        "fan_add_q_btn": "➕ Savol qo'shish",
        "fan_activate_btn": "✅ Faollashtirish",
        "fan_deactivate_btn": "❌ Nofaollashtirish",
        "fan_delete_btn": "🗑 Fanni o'chirish",
        "fan_del_ask": "🗑 <b>{name}</b> fanini o'chirmoqchimisiz?\n\n⚠️ Bog'liq savollar saqlanib qoladi, fan ro'yxatdan o'chadi.",
        "fan_deleted": "✅ Fan o'chirildi: <b>{name}</b>",
        "fan_toggled_on": "✅ Fan faollashtirildi: <b>{name}</b>",
        "fan_toggled_off": "❌ Fan nofaollashtirildi: <b>{name}</b>",
        "del_confirm_btn": "🗑 Ha, o'chirish",
        "del_cancel_btn": "❌ Bekor qilish",
        # Sinf boshqaruvi
        "cls_detail": "🏫 <b>{name}</b>\n👥 O'quvchilar: {n} ta\n🔘 Holat: {status}",
        "cls_edit_btn": "✏️ Nomini tahrirlash",
        "cls_edit_ask": "✏️ <b>{name}</b> sinfining yangi nomini yozing:",
        "cls_edited": "✅ Sinf nomi o'zgartirildi: <b>{name}</b>",
        "cls_activate_btn": "✅ Faollashtirish",
        "cls_deactivate_btn": "❌ Nofaollashtirish",
        "cls_delete_btn": "🗑 Sinfni o'chirish",
        "cls_view_students_btn": "👥 O'quvchilar",
        "cls_del_ask": "🗑 <b>{name}</b> sinfini o'chirmoqchimisiz?\n\n⚠️ Sinfdagi barcha o'quvchilar ham o'chiriladi!",
        "cls_deleted": "✅ Sinf o'chirildi: <b>{name}</b>",
        "cls_toggled_on": "✅ Sinf faollashtirildi: <b>{name}</b>",
        "cls_toggled_off": "❌ Sinf nofaollashtirildi: <b>{name}</b>",
        # O'quvchi boshqaruvi
        "std_detail": "👤 <b>{last} {first}</b>\n🏫 Sinf: {cls}\n📱 Ota-ona TG: {parent}",
        "std_edit_fname_btn": "✏️ Ismni o'zgartirish",
        "std_edit_lname_btn": "✏️ Familiyani o'zgartirish",
        "std_edit_parent_btn": "📱 TG ID o'zgartirish",
        "std_delete_btn": "🗑 O'quvchini o'chirish",
        "std_del_ask": "🗑 <b>{last} {first}</b>ni o'chirmoqchimisiz?",
        "std_deleted": "✅ O'quvchi o'chirildi: <b>{last} {first}</b>",
        "std_edit_ask_fname": "✏️ Yangi <b>ismni</b> kiriting:",
        "std_edit_ask_lname": "✏️ Yangi <b>familiyani</b> kiriting:",
        "std_edit_ask_parent": "📱 Yangi Telegram ID kiriting\n(yoki <b>O'chirish</b> bosing TG ID ni olib tashlash uchun):",
        "std_updated": "✅ O'quvchi yangilandi: <b>{last} {first}</b>",
    }
}


def T(user_lang: str, key: str, **kwargs) -> str:
    lang = user_lang if user_lang in TEXTS else "ru"
    text = TEXTS[lang].get(key, TEXTS["ru"].get(key, key))
    return text.format(**kwargs) if kwargs else text
