"""
Bot xabarlari — O'zbek va Rus tillarida.
"""

TEXTS = {
    "ru": {
        "start_new": "👋 Добро пожаловать в <b>Саломат билимдонлари</b>!\n\nВыберите язык:",
        "start_welcome_parent": "👋 Добро пожаловать, {name}!\n\n📊 Вы вошли как <b>родитель</b>.",
        "start_welcome_admin": "👋 Добро пожаловать, <b>Администратор</b>!\n\nВы вошли в <b>Панель управления</b>.",
        "lang_changed": "✅ Язык изменён на Русский",
        "no_children": "😔 Ваш Telegram ID не привязан ни к одному ученику.\n\n📋 Сообщите учителю ваш Chat ID: <code>{chat_id}</code>\nПопросите добавить его в профиль вашего ребёнка.",
        "children_list": "👨‍👩‍👧 <b>Ваши дети:</b>",
        "child_results_title": "📊 <b>Результаты: {name} {last}</b> ({cls})\n\n",
        "no_results": "📭 Пока нет результатов для этого ученика.",
        "result_row": "📝 <b>{test}</b>\n   📊 {score:.1f}% | {grade} | {status}\n   🕐 {date}\n\n",
        "passed": "✅ Сдал",
        "failed": "❌ Не сдал",
        "back": "⬅️ Назад",
        "main_menu": "🏠 Главное меню",
        "settings_btn": "⚙️ Настройки",
        "lang_btn": "🌐 Сменить язык",
        "children_btn": "👨‍👩‍👧 Мои дети",
        "results_btn": "📊 Результаты",
        "not_admin": "❌ У вас нет прав администратора.",
        "admin_menu_title": "🔧 <b>Панель администратора</b>\n\nВыберите раздел:",
        "stats_btn": "📈 Статистика",
        "students_btn": "👥 Ученики",
        "questions_btn": "❓ Вопросы",
        "subjects_btn": "📚 Предметы",
        "top_btn": "🏆 Топ учеников",
        "broadcast_btn": "📢 Рассылка",
        "admins_btn": "👤 Администраторы",
        "stats_title": "📈 <b>Общая статистика</b>\n\n",
        "stats_total_exams": "📝 Всего экзаменов: <b>{n}</b>\n",
        "stats_passed": "✅ Сдали: <b>{n}</b>\n",
        "stats_failed": "❌ Не сдали: <b>{n}</b>\n",
        "stats_avg": "📊 Средний балл: <b>{v:.1f}%</b>\n",
        "stats_students": "👥 Учеников: <b>{n}</b>\n",
        "stats_classes": "🏫 Классов: <b>{n}</b>\n",
        "stats_questions": "❓ Вопросов: <b>{n}</b>\n",
        "top_title": "🏆 <b>Топ 10 учеников</b>\n\n",
        "top_row": "{rank}. <b>{last} {first}</b> ({cls}) — {score:.1f}% | {test}\n",
        "no_top": "Пока нет данных.",
        "subjects_title": "📚 <b>Предметы ({n}):</b>\n\n",
        "subject_row": "• {name} — {q} вопросов\n",
        "no_subjects": "Предметов пока нет.",
        "broadcast_ask": "📢 <b>Рассылка родителям</b>\n\nНапишите сообщение для отправки всем родителям:",
        "broadcast_confirm": "📢 Отправить это сообщение <b>{n} родителям</b>?\n\n<i>{text}</i>",
        "broadcast_sent": "✅ Сообщение отправлено {ok} из {total} родителям.",
        "broadcast_cancel": "❌ Рассылка отменена.",
        "confirm_btn": "✅ Подтвердить",
        "cancel_btn": "❌ Отмена",
        "add_question_btn": "➕ Добавить вопрос",
        "q_choose_subject": "📚 Выберите предмет для вопроса:",
        "q_ask_text": "✏️ Введите текст вопроса:",
        "q_ask_a": "✅ Введите вариант <b>A</b>:",
        "q_ask_b": "📘 Введите вариант <b>B</b>:",
        "q_ask_c": "🟠 Введите вариант <b>C</b>:",
        "q_ask_d": "🔴 Введите вариант <b>D</b>:",
        "q_ask_correct": "✔️ Какой вариант правильный? Выберите:",
        "q_ask_diff": "📊 Выберите сложность:",
        "q_diff_easy": "🟢 Лёгкий",
        "q_diff_med": "🟡 Средний",
        "q_diff_hard": "🔴 Сложный",
        "q_confirm": "✅ <b>Проверьте вопрос:</b>\n\n📝 {text}\n\nA: {a}\nB: {b}\nC: {c}\nD: {d}\n\n✔️ Правильный: <b>{correct}</b>\n📊 Сложность: {diff}",
        "q_saved": "✅ Вопрос успешно сохранён! (ID: {id})",
        "q_cancel": "❌ Добавление вопроса отменено.",
        "admins_title": "👤 <b>Бот-администраторы:</b>\n\n{list}\n\n<i>Для добавления — введите Telegram ID в настройках десктоп-приложения</i>",
        "no_admins": "Администраторов пока нет.",
        "admin_row": "• <code>{tid}</code>\n",
        "students_classes": "🏫 <b>Классы:</b>",
        "class_row": "• {name} — {n} учеников",
        "students_of_class": "👥 <b>Ученики класса {cls}:</b>\n\n",
        "student_row": "{i}. {last} {first}",
        "no_students_in_class": "В этом классе пока нет учеников.",
        "error": "❌ Произошла ошибка. Попробуйте снова.",
        "refresh_btn": "🔄 Обновить",
        "close_btn": "✖ Закрыть",
        # Fan yaratish
        "fan_add_btn": "➕ Добавить предмет",
        "fan_add_ask_name": "📚 Введите название предмета:",
        "fan_add_ask_time": "⏱ Введите лимит времени в минутах (например: <b>30</b>):",
        "fan_add_time_invalid": "❌ Введите только число (например: 30):",
        "fan_add_confirm": "✅ <b>Добавить предмет?</b>\n\n📚 Название: <b>{name}</b>\n⏱ Время: <b>{time} мин</b>",
        "fan_add_saved": "✅ Предмет добавлен: <b>{name}</b>",
        "fan_add_cancel": "❌ Добавление предмета отменено.",
        # Sinf qo'shish
        "cls_add_btn": "➕ Добавить класс",
        "cls_add_ask_name": "🏫 Введите название класса (например: <b>9-A</b>):",
        "cls_add_confirm": "✅ <b>Добавить класс?</b>\n\n🏫 Название: <b>{name}</b>",
        "cls_add_saved": "✅ Класс добавлен: <b>{name}</b>",
        "cls_add_cancel": "❌ Добавление класса отменено.",
        # O'quvchi qo'shish
        "std_add_btn": "➕ Добавить ученика",
        "std_add_ask_fname": "👤 Введите <b>имя</b> ученика:",
        "std_add_ask_lname": "👤 Введите <b>фамилию</b> ученика:",
        "std_add_ask_parent": "📱 Введите Telegram ID родителя\n(или нажмите <b>Пропустить</b>):",
        "std_add_skip_btn": "⏭ Пропустить",
        "std_add_confirm": (
            "✅ <b>Добавить ученика?</b>\n\n"
            "👤 Имя: <b>{first}</b>\n"
            "👤 Фамилия: <b>{last}</b>\n"
            "🏫 Класс: <b>{cls}</b>\n"
            "📱 Telegram ID родителя: <b>{parent}</b>"
        ),
        "std_add_saved": "✅ Ученик добавлен: <b>{last} {first}</b> → {cls}",
        "std_add_cancel": "❌ Добавление ученика отменено.",
    },
    "uz": {
        "start_new": "👋 <b>Salomat bilimdonlari</b> ga xush kelibsiz!\n\nTilni tanlang:",
        "start_welcome_parent": "👋 Xush kelibsiz, {name}!\n\n📊 Siz <b>ota-ona</b> sifatida kirdingiz.",
        "start_welcome_admin": "👋 Xush kelibsiz, <b>Administrator</b>!\n\n<b>Boshqaruv paneli</b> ga xush kelibsiz.",
        "lang_changed": "✅ Til O'zbekchaga o'zgartirildi",
        "no_children": "😔 Sizning Telegram ID hech bir o'quvchiga biriktirilmagan.\n\n📋 O'qituvchiga Chat ID ni bering: <code>{chat_id}</code>\nO'quvchi profiliga kiritishni so'rang.",
        "children_list": "👨‍👩‍👧 <b>Farzandlaringiz:</b>",
        "child_results_title": "📊 <b>Natijalar: {name} {last}</b> ({cls})\n\n",
        "no_results": "📭 Bu o'quvchi uchun hali natijalar yo'q.",
        "result_row": "📝 <b>{test}</b>\n   📊 {score:.1f}% | {grade} | {status}\n   🕐 {date}\n\n",
        "passed": "✅ O'tdi",
        "failed": "❌ O'tmadi",
        "back": "⬅️ Orqaga",
        "main_menu": "🏠 Asosiy menyu",
        "settings_btn": "⚙️ Sozlamalar",
        "lang_btn": "🌐 Tilni o'zgartirish",
        "children_btn": "👨‍👩‍👧 Farzandlarim",
        "results_btn": "📊 Natijalar",
        "not_admin": "❌ Sizda admin huquqi yo'q.",
        "admin_menu_title": "🔧 <b>Admin paneli</b>\n\nBo'limni tanlang:",
        "stats_btn": "📈 Statistika",
        "students_btn": "👥 O'quvchilar",
        "questions_btn": "❓ Savollar",
        "subjects_btn": "📚 Fanlar",
        "top_btn": "🏆 Top o'quvchilar",
        "broadcast_btn": "📢 Xabar yuborish",
        "admins_btn": "👤 Adminlar",
        "stats_title": "📈 <b>Umumiy statistika</b>\n\n",
        "stats_total_exams": "📝 Jami imtihonlar: <b>{n}</b>\n",
        "stats_passed": "✅ O'tdilar: <b>{n}</b>\n",
        "stats_failed": "❌ O'tmadilar: <b>{n}</b>\n",
        "stats_avg": "📊 O'rtacha ball: <b>{v:.1f}%</b>\n",
        "stats_students": "👥 O'quvchilar: <b>{n}</b>\n",
        "stats_classes": "🏫 Sinflar: <b>{n}</b>\n",
        "stats_questions": "❓ Savollar: <b>{n}</b>\n",
        "top_title": "🏆 <b>Top 10 O'quvchilar</b>\n\n",
        "top_row": "{rank}. <b>{last} {first}</b> ({cls}) — {score:.1f}% | {test}\n",
        "no_top": "Hozircha ma'lumot yo'q.",
        "subjects_title": "📚 <b>Fanlar ({n}):</b>\n\n",
        "subject_row": "• {name} — {q} ta savol\n",
        "no_subjects": "Hozircha fan yo'q.",
        "broadcast_ask": "📢 <b>Ota-onalarga xabar</b>\n\nBarcha ota-onalarga yuboriladigan xabarni yozing:",
        "broadcast_confirm": "📢 Bu xabarni <b>{n} ta ota-onaga</b> yuborasizmi?\n\n<i>{text}</i>",
        "broadcast_sent": "✅ Xabar {ok} ta ota-onadan {total} tasiga yuborildi.",
        "broadcast_cancel": "❌ Xabar yuborish bekor qilindi.",
        "confirm_btn": "✅ Tasdiqlash",
        "cancel_btn": "❌ Bekor qilish",
        "add_question_btn": "➕ Savol qo'shish",
        "q_choose_subject": "📚 Savol uchun fan tanlang:",
        "q_ask_text": "✏️ Savol matnini kiriting:",
        "q_ask_a": "✅ <b>A</b> variantini kiriting:",
        "q_ask_b": "📘 <b>B</b> variantini kiriting:",
        "q_ask_c": "🟠 <b>C</b> variantini kiriting:",
        "q_ask_d": "🔴 <b>D</b> variantini kiriting:",
        "q_ask_correct": "✔️ Qaysi variant to'g'ri? Tanlang:",
        "q_ask_diff": "📊 Qiyinlikni tanlang:",
        "q_diff_easy": "🟢 Oson",
        "q_diff_med": "🟡 O'rta",
        "q_diff_hard": "🔴 Qiyin",
        "q_confirm": "✅ <b>Savolni tekshiring:</b>\n\n📝 {text}\n\nA: {a}\nB: {b}\nC: {c}\nD: {d}\n\n✔️ To'g'ri: <b>{correct}</b>\n📊 Qiyinlik: {diff}",
        "q_saved": "✅ Savol muvaffaqiyatli saqlandi! (ID: {id})",
        "q_cancel": "❌ Savol qo'shish bekor qilindi.",
        "admins_title": "👤 <b>Bot-adminlar:</b>\n\n{list}\n\n<i>Qo'shish uchun — Telegram ID ni desktop dastur sozlamalarida kiriting</i>",
        "no_admins": "Hozircha admin yo'q.",
        "admin_row": "• <code>{tid}</code>\n",
        "students_classes": "🏫 <b>Sinflar:</b>",
        "class_row": "• {name} — {n} ta o'quvchi",
        "students_of_class": "👥 <b>{cls} sinf o'quvchilari:</b>\n\n",
        "student_row": "{i}. {last} {first}",
        "no_students_in_class": "Bu sinfda hozircha o'quvchi yo'q.",
        "error": "❌ Xato yuz berdi. Qayta urinib ko'ring.",
        "refresh_btn": "🔄 Yangilash",
        "close_btn": "✖ Yopish",
        # Fan yaratish
        "fan_add_btn": "➕ Fan qo'shish",
        "fan_add_ask_name": "📚 Fan nomini kiriting:",
        "fan_add_ask_time": "⏱ Vaqt chegarasini daqiqada kiriting (masalan: <b>30</b>):",
        "fan_add_time_invalid": "❌ Faqat son kiriting (masalan: 30):",
        "fan_add_confirm": "✅ <b>Fan qo'shilsinmi?</b>\n\n📚 Nom: <b>{name}</b>\n⏱ Vaqt: <b>{time} daqiqa</b>",
        "fan_add_saved": "✅ Fan qo'shildi: <b>{name}</b>",
        "fan_add_cancel": "❌ Fan qo'shish bekor qilindi.",
        # Sinf qo'shish
        "cls_add_btn": "➕ Sinf qo'shish",
        "cls_add_ask_name": "🏫 Sinf nomini kiriting (masalan: <b>9-A</b>):",
        "cls_add_confirm": "✅ <b>Sinf qo'shilsinmi?</b>\n\n🏫 Nom: <b>{name}</b>",
        "cls_add_saved": "✅ Sinf qo'shildi: <b>{name}</b>",
        "cls_add_cancel": "❌ Sinf qo'shish bekor qilindi.",
        # O'quvchi qo'shish
        "std_add_btn": "➕ O'quvchi qo'shish",
        "std_add_ask_fname": "👤 O'quvchining <b>ismini</b> kiriting:",
        "std_add_ask_lname": "👤 O'quvchining <b>familiyasini</b> kiriting:",
        "std_add_ask_parent": "📱 Ota-ona Telegram ID sini kiriting\n(yoki <b>O'tkazib yuborish</b> bosing):",
        "std_add_skip_btn": "⏭ O'tkazib yuborish",
        "std_add_confirm": (
            "✅ <b>O'quvchi qo'shilsinmi?</b>\n\n"
            "👤 Ismi: <b>{first}</b>\n"
            "👤 Familiyasi: <b>{last}</b>\n"
            "🏫 Sinf: <b>{cls}</b>\n"
            "📱 Ota-ona Telegram ID: <b>{parent}</b>"
        ),
        "std_add_saved": "✅ O'quvchi qo'shildi: <b>{last} {first}</b> → {cls}",
        "std_add_cancel": "❌ O'quvchi qo'shish bekor qilindi.",
    }
}


def T(user_lang: str, key: str, **kwargs) -> str:
    lang = user_lang if user_lang in TEXTS else "ru"
    text = TEXTS[lang].get(key, TEXTS["ru"].get(key, key))
    return text.format(**kwargs) if kwargs else text
